# A reusable workflow that can ping the Supabase project for a given environment
# to prevent it from becoming paused.
name: 'Ping Supabase'

on:
  workflow_call:
    inputs:
      environment-name:
        type: string
        required: true

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_KEY: ${{ vars.SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install @supabase/supabase-js
      - run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
          const { data, error } = supabase.from('keep_alive').select().limit(1);

          if(data) {
            console.log(data);
          }

          if(error) {
            console.error(error);
            process.exit(1)
          }
          "
